language: ruby
rvm:
  - 2.2
sudo: false


branches:
  only:
  - master
install:
  - bundle install --jobs=3 --retry=3 --deployment
before_script:
  - bundle exec "jekyll serve --incremental --safe"
script:
  - bundle exec "rake check_links"