language: ruby
rvm:
  - 2.2
branches:
  only:
  - master
script:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec "jekyll serve --incremental --safe"
  - bundle exec "rake check_links"