language: ruby
rvm:
  - 2.2
sudo: false

exclude:
- Gemfile.lock
- vendor

branches:
  only:
  - master
install:
  - bundle install --jobs=3 --retry=3 --deployment
script:
  - bundle exec "jekyll serve --incremental --safe"
  - bundle exec "rake check_links"